app/user_management/forms.py
""" Forms for User Management """

from flask_wtf import FlaskForm
from wtforms import SubmitField, TextField, validators
from wtforms.fields import StringField, SelectField
from wtforms.widgets import TextArea


class EditUserForm(FlaskForm):
    """ Form to edit a User """

    name = StringField("Name", [validators.Length(min=0, max=45), validators.DataRequired()])
    email = StringField("Email", [validators.Length(min=1, max=320), validators.Email()])
    username = StringField("Username", [validators.Length(min=1, max=45)])
    submit = SubmitField('Submit')



class AddAllergyForm(FlaskForm):
    """ Form to edit an Allergy owned by a user """
    allergy_id = SelectField("Allergy", coerce=int )
    submit = SubmitField('Submit')

app/user_management/__init__.py
""" User Management module provides endpoints for the managing a User """

from flask import Blueprint

user_mgmt = Blueprint('user_mgmt', __name__) # pylint: disable=C0103

from app.user_management import views #pylint: disable=C0413

app/user_management/views.py
""" Views associated with user managemetn """

from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required
from flask.ext.login import current_user

from app.user_management import user_mgmt
from app.user_management.forms import EditUserForm, AddAllergyForm
from operations.core import user_modify, user_lookup, user_allergy_modify, allergy_lookup, user_allergy_lookup
from models.core.user_allergy import UserAllergy

@user_mgmt.route('/user/')
def view():
    """ View your User profile """

    user_obj = user_lookup.by_id(current_user.id)
    return render_template('user_management/view.html', var={'user_obj':user_obj})


@user_mgmt.route('/user/edit', methods=['POST', 'GET'])
def edit():
    """ Edit your User profile """
    form = EditUserForm(request.form)

    if request.method == "POST":
        if form.validate_on_submit():
            user_modify.save(current_user.id, request.form)
            return redirect(url_for('user_mgmt.view'))
    else:
        form = EditUserForm(obj=current_user)

    return render_template('user_management/edit.html', var={'form':form} )


@user_mgmt.route('/user/allergy', methods=['POST', 'GET'])
def add_allergy():
    """ Add an allergy to the User """
    form = AddAllergyForm(request.form)

    # Set the allergies to be shown
    user_allergies = [a.allergy.id for a in allergy_lookup.get_user_allergies(current_user.id)]
    form.allergy_id.choices = [(a.id, a.name) for a in allergy_lookup.get_non_allergies(user_allergies)]

    if request.method == "POST":
        if form.validate_on_submit():
            user_allergy_modify.add(current_user.id, request.form)
            return redirect(url_for('user_mgmt.view'))

    return render_template('user_management/add_allergy.html', var={'form':form} )


@user_mgmt.route('/user/delete_allergy', methods=['POST'])
@login_required
def delete_allergy():
    """ Delete a specific recipe """
    if request.method == 'POST':
        allergy_id = request.form['allergy_id']
        user_allergy_obj = user_allergy_lookup.by_user_allergy(current_user.id, allergy_id)
        if user_allergy_obj:
            user_allergy_modify.delete(user_allergy_obj)
            flash("Successfully deleted Allergy")

    return redirect(url_for('user_mgmt.view'))

app/templates/user_management/add_allergy.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block title %}Add Allergy to your profile{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
      {% for field, errors in var.form.errors.iteritems() %}
        <div class="alert alert-error">
            {{ var.form[field].label }}: {{ ', '.join(errors) }}
        </div>
      {% endfor %}
      {{ utils.flashed_messages() }}
      <form action="{{ url_for('user_mgmt.add_allergy') }}" method="post">
        {{ var.form.hidden_tag() }}
        {{ var.form.csrf_token }}
        <legend>Add Allergy</legend>
        {{ wtf.form_field(var.form.allergy_id, class='form-control') }}
        {{ render_field(var.form.submit, class='btn btn-success btn-block') }}
      </form>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}

app/templates/user_management/edit.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block title %}Edit Your Profile{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
      {% for field, errors in var.form.errors.iteritems() %}
        <div class="alert alert-error">
            {{ var.form[field].label }}: {{ ', '.join(errors) }}
        </div>
      {% endfor %}
      {{ utils.flashed_messages() }}
      <form action="{{ url_for('user_mgmt.edit') }}" method="post">
        {{ var.form.hidden_tag() }}
        <legend>Edit Profile</legend>
        {{ wtf.form_field(var.form.name, class='form-control') }}
        {{ wtf.form_field(var.form.email, class='form-control') }}
        {{ wtf.form_field(var.form.username, class='form-control') }}
        {{ render_field(var.form.submit, class='btn btn-success btn-block') }}
      </form>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}

app/templates/user_management/view.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block title %}User Information{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    {{ utils.flashed_messages() }}
    <div class="col-md-1"></div>
    <h2>
      Your profile
      <a href="{{ url_for('user_mgmt.edit') }}" class="btn btn-warning">Edit</a>
      <a href="{{ url_for('user_mgmt.add_allergy') }}" class="btn btn-successful">Add Allergy</a>
    </h2>
    <ui>
      <li>Email - {{ var.user_obj.email }}</li>
      <li>Name - {{ var.user_obj.name }}</li>
      <li>Username - {{ var.user_obj.username }}</li>
    </ui>

    Allergies
    <ui>
      {% for allergy in var.user_obj.allergies %}
        <li>
          {{ allergy.name }}
          <form action="{{ url_for('user_mgmt.delete_allergy') }}" method="post" style='display:inline;margin:0px;padding:0px;'>
            <input type="hidden" name ="allergy_id" value="{{ allergy.allergy_id }}" />
            <button type="submit" name ="submit" class="btn btn-danger">DELETE</button>
          </form>
        </li>


      {% endfor %}
    </ui>



    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}