app/recipe/forms.py
""" Forms for recipe """

from flask_wtf import FlaskForm
from wtforms import SubmitField, TextField, validators, SelectField
from wtforms.fields import StringField
from wtforms.widgets import TextArea

class URLForm(FlaskForm):
    """ Form to ask user for URL to use """
    choices = [
        ('1', 'Breakfast'),
        ('2', 'Lunch'),
        ('3', 'Dinner')
    ]

    URL = TextField('URL')
    category_id = SelectField("Category", choices=choices)
    submit = SubmitField('Submit')

    # def validate(self):
    #     """ Validation to ensure url is entered """
    #     return len(URL) > 0 and URL is not None


class EditRecipeForm(FlaskForm):
    """ Form to edit a Recipe name """
    name = TextField("Name", [validators.Length(min=1, max=200)])
    description = StringField("Description", [validators.Length(min=0, max=500)], widget=TextArea())
    submit = SubmitField('Submit')


class EditRecipeStepForm(FlaskForm):
    """ Form to edit a RecipeStep """
    description = StringField("Description", widget=TextArea())
    submit = SubmitField('Submit')


class EditIngredientForm(FlaskForm):
    """ Form to edit an Ingredient """
    description = TextField("Description", [validators.Length(min=5, max=100)])
    submit = SubmitField('Submit')

app/recipe/__init__.py
""" Recipe module provides endpoints for the creating/editing recipes """

from flask import Blueprint

recipe = Blueprint('recipe', __name__) # pylint: disable=C0103

from app.recipe import views #pylint: disable=C0413

app/recipe/views.py
""" Views associated with recipe """

from flask import render_template, request, url_for, redirect, flash
from flask_login import login_required
from flask.ext.login import current_user

from app.recipe import recipe
from app.recipe.forms import URLForm, EditRecipeForm, EditRecipeStepForm, EditIngredientForm
from operations.helper import url_parse

from operations.recipe import recipe_lookup, recipe_modify, recipe_step_lookup, \
                               recipe_step_modify, quantity_lookup, quantity_modify

@recipe.route('/recipe/add', methods=['GET', 'POST'])
@login_required
def add():
    """ Add a Recipe """
    form = URLForm(request.form)

    if request.method == "POST":
        if form.validate_on_submit():
            #If this is not a valid recipe, return a defualt message
            try:
              sucessful, recipe_id = url_parse.allrecipes(request.form['URL'], request.form['category_id'], current_user.id)

              #if not sucessful, tell user they already have the object
              if not sucessful:
                  flash('Already have that recipe')
                  return render_template('recipe/add_recipe.html', form=form)
              return redirect(url_for('recipe.view', recipe_id=recipe_id))

            except:
              flash('ERROR: This is not a valid recipe!')
              return render_template('recipe/add_recipe.html', form=form)


    return render_template('recipe/add_recipe.html', form=form)

@recipe.route('/recipe/view/', methods=['GET'])
@login_required
def view():
    """ View a specific Recipe """
    recipe_obj = recipe_lookup.by_id(request.args.get('recipe_id'))
    return render_template('recipe/view.html', recipe=recipe_obj)


# Add decorator to ensure user own's this recipe
@recipe.route('/recipe/edit_recipe/', methods=['GET', 'POST'])
@login_required
def edit_recipe():
    """ Edit a Recipe Name """
    form = EditRecipeForm(request.form)
    recipe_obj = recipe_lookup.by_id(request.args.get('recipe_id'))

    if request.method == "POST":
        if form.validate_on_submit():
            recipe_modify.save(recipe_obj, request.form)
            return redirect(url_for('recipe.view', recipe_id=recipe_obj.id))
    else:
        form = EditRecipeForm(obj=recipe_obj)

    return render_template('recipe/edit_recipe.html', \
                            var={'form':form,
                                 'recipe_id':recipe_obj.id
                                }
                          )



# TODO: Add decorator to ensure user own's this recipe
@recipe.route('/recipe/edit_step/', methods=['GET', 'POST'])
@login_required
def edit_step():
    """ Edit a Recipe Step """
    form = EditRecipeStepForm(request.form)
    recipe_step = recipe_step_lookup.by_id(request.args.get('recipe_step_id'))

    if request.method == "POST":
        if form.validate_on_submit():
            recipe_step_modify.save(recipe_step, request.form)
            return redirect(url_for('recipe.view', recipe_id=recipe_step.recipe_id))
    else:
        form = EditRecipeStepForm(obj=recipe_step)

    return render_template('recipe/edit_recipe_step.html', \
                            var={'form':form, 'recipe_step_id':recipe_step.id})


# TODO: Add decorator to ensure user own's this recipe
@recipe.route('/recipe/edit_ingrd/', methods=['GET', 'POST'])
@login_required
def edit_ingredient():
    """ Edit an Ingredient """
    form = EditIngredientForm(request.form)
    ingredient = quantity_lookup.by_id(request.args.get('quantity_id'))
    if request.method == "POST":
        if form.validate_on_submit():
            quantity_modify.save(ingredient, request.form)
            return redirect(url_for('recipe.view', recipe_id=ingredient.recipe_id))
    else:
        form = EditIngredientForm(description=ingredient.description())

    return render_template('recipe/edit_ingredient.html', \
                            var={'form':form, 'quantity_id':ingredient.id})




@recipe.route('/recipe/view_all')
@login_required
def view_all():
    """ View all Recipes """
    all_recipes = recipe_lookup.get_all(current_user.id)

    return render_template('recipe/view_all.html', all_recipes=all_recipes)



@recipe.route('/recipe/delete_recipe', methods=['POST'])
@login_required
def delete_recipe():
    """ Delete a specific recipe """
    if request.method == 'POST':
        recipe_id = request.form['recipe_id']
        recipe = recipe_lookup.by_user_recipe_id(current_user.id, recipe_id)
        if recipe:
            recipe_modify.delete(recipe)
            flash("Successfully deleted recipe")

    return redirect(url_for('recipe.view_all'))


@recipe.route('/recipe/delete_ingredient', methods=['POST'])
@login_required
def delete_ingredient():
    """ Delete a specific ingredient """
    if request.method == 'POST':
        quantity_id = request.form['quantity_id']
        recipe_id = request.form['recipe_id']
        quantity = quantity_lookup.by_id(quantity_id)
        if quantity:
            quantity_modify.delete(quantity)
            flash("Successfully deleted ingredient")

        return redirect(url_for('recipe.view', recipe_id=recipe_id))

    return redirect(url_for('recipe.view_all'))




@recipe.route('/recipe/category/', methods=['GET'])
@login_required
def view_category():
    """ View a  Recipe """
    category = request.args.get('category_id')
    all_recipes = recipe_lookup.by_category(category)

    return render_template('recipe/view_all.html', all_recipes=all_recipes)

app/templates/recipe/add_recipe.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block title %}Parse URL{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
      {% for field, errors in form.errors.iteritems() %}
        <div class="alert alert-error">
            {{ form[field].label }}: {{ ', '.join(errors) }}
        </div>
      {% endfor %}
      {{ utils.flashed_messages() }}
      <form action="{{ url_for('recipe.add') }}" method="post">
        {{ form.hidden_tag() }}
        <legend>Recipe from URL to add</legend>
        {{ wtf.form_field(form.URL, class='form-control', placeholder='Enter the URL to parse here') }}
        {{ wtf.form_field(form.category_id, class='form-control') }}
        {{ render_field(form.submit, class='btn btn-success btn-block') }}
      </form>
      <br><br>
      <h4>Shortcuts to Recipe Source Websites</h4>
      <a href="https://www.allrecipes.com/"  target="_blank" ><button class="btn btn-info">AllRecipes.com</button></a>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}

app/templates/recipe/dashboard.html
{% extends "sidebar.html" %}
Recipe
{% block content %}
{% endblock %}

app/templates/recipe/edit_ingredient.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block title %}Edit Ingredient{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
      {% for field, errors in var.form.errors.iteritems() %}
        <div class="alert alert-error">
            {{ var.form[field].label }}: {{ ', '.join(errors) }}
        </div>
      {% endfor %}
      {{ utils.flashed_messages() }}
      <form action="{{ url_for('recipe.edit_ingredient', quantity_id=var.quantity_id) }}" method="post">
        {{ var.form.hidden_tag() }}
        <legend>Edit Ingredient</legend>
        {{ wtf.form_field(var.form.description, class='form-control') }}
        {{ render_field(var.form.submit, class='btn btn-success btn-block') }}
      </form>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}

app/templates/recipe/edit_recipe.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block title %}Edit Recipe{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
      {% for field, errors in var.form.errors.iteritems() %}
        <div class="alert alert-error">
            {{ var.form[field].label }}: {{ ', '.join(errors) }}
        </div>
      {% endfor %}
      {{ utils.flashed_messages() }}
      <form action="{{ url_for('recipe.edit_recipe', recipe_id=var.recipe_id) }}" method="post">
        {{ var.form.hidden_tag() }}
        <legend>Edit Recipe Name and Description</legend>
        {{ wtf.form_field(var.form.name, class='form-control') }}
        {{ wtf.form_field(var.form.description, class='form-control', rows=5) }}
        {{ render_field(var.form.submit, class='btn btn-success btn-block') }}
      </form>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}

app/templates/recipe/edit_recipe_step.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block title %}Edit Recipe Step{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
      {% for field, errors in var.form.errors.iteritems() %}
        <div class="alert alert-error">
            {{ var.form[field].label }}: {{ ', '.join(errors) }}
        </div>
      {% endfor %}
      {{ utils.flashed_messages() }}
      <form action="{{ url_for('recipe.edit_step', recipe_step_id=var.recipe_step_id) }}" method="post">
        {{ var.form.hidden_tag() }}
        <legend>Edit Recipe Step</legend>
        {{ wtf.form_field(var.form.description, class='form-control', rows=5) }}
        {{ render_field(var.form.submit, class='btn btn-success btn-block') }}
      </form>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}

app/templates/recipe/index.html
{% extends "sidebar.html" %}

{% block content %}
This is recipe
{% endblock %}

app/templates/recipe/view.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}

{% block styles %}
  {{ super() }}
  <style>
    .edit_button { display:none; }
    #check_off { display:inline; }
  </style>
  <link rel='stylesheet' href="{{ url_for('static', filename='stylesheets/checkboxes.css') }}" />

{% endblock %}

{% block scripts %}
  {{ super() }}
  <script>
  function edit_recipe(){
    var buttons = document.getElementsByClassName('edit_button');
    for(var i = 0; i < buttons.length; i++){
      buttons[i].style.display="inline";
    }

    var checkboxes = document.getElementsByClassName('checkmark');
    for(var i = 0; i < checkboxes.length; i++){
      checkboxes[i].style.display="none";
    }

    document.getElementById('editable').style.display="none";
  }
  </script>
{% endblock %}

{% block title %}View Recipe{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    {{ utils.flashed_messages() }}
    <br>
    <div class="col-md-1"></div>
    <img src="{{ recipe.img_path }}"/>
    <h2>Viewing specific recipe</h2>

    {% if current_user.id == recipe.user_id %}
    <button type="button" onclick="edit_recipe()" id="editable" class="btn btn-info">
      <span class="glyphicon glyphicon-edit"></span> Edit this recipe.
    </button>
    {% endif %}
    <br>
    <table>
        <a href="{{ url_for('recipe.edit_recipe', recipe_id=recipe.id) }}" class='edit_button' style="text-decoration: none;">
          <button type="submit" name ="quantity_id" class="btn btn-info"><span class="glyphicon glyphicon-edit"></span></button>
        </a>
        <h3 style="display: inline;"><b>{{ recipe.name }}</b></h3>

      <ul>
        {% for step in recipe.steps %}
        <label class="container"><b>{{ step.num }}</b> - {{ step.description }}
            <input type="checkbox">
            <span class="checkmark"></span>
          <a href="{{ url_for('recipe.edit_step', recipe_step_id=step.id) }}" class='edit_button' style="display: contents; font-family: Ariel;">
            <button type="submit" name ="quantity_id" class="btn btn-info" style="padding: 5px; padding-bottom: 2px;">
              <span class="glyphicon glyphicon-edit"></span>
            </button>
          </a>
          </label>
        {% endfor %}
      <ul>
    </table>

    <table>
          <h2>Ingredients</h2>
          {% for ingredient in recipe.quantity %}
          <li style="padding-bottom:5px;">
            <a href="{{ url_for('recipe.edit_ingredient', quantity_id=ingredient.id) }}" class='edit_button' style="text-decoration: none;">
              <button type="submit" name ="quantity_id" class="btn btn-info" style="padding: 5px; padding-bottom: 2px;"><span class="glyphicon glyphicon-edit"></span></button>
            </a>
            <form action="{{ url_for('recipe.delete_ingredient') }}" method="post" style='display:inline;margin:0px;padding:0px;'>
              <input type="hidden" name ="recipe_id" value="{{ recipe.id }}" />
              <input type="hidden" name ="quantity_id" value="{{ ingredient.id }}" />
              <button type="submit" name ="submit" value="submit" class="btn btn-danger edit_button" style="padding: 5px; padding-bottom: 2px;"><span class="glyphicon glyphicon-trash"></span></button>
            </form>
            {{ ingredient.amount }} {{ ingredient.measurement_obj.name }} {{ ingredient.ingredient_obj.name }}

          </li>
          {% endfor %}
        </ul>
      </ul>
    </table>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}

app/templates/recipe/view_all.html
{% extends "sidebar.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}


{% block title %}View All Recpies{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    {{ utils.flashed_messages() }}
    <br>
    <table>
      {% for recipe in all_recipes %}
        <li>
          <a href="{{ url_for('recipe.view', recipe_id=recipe.id) }}">
             <button type="submit" name ="quantity_id" class="btn btn-info" style="padding: 5px; padding-bottom: 2px;"><span class="glyphicon glyphicon-edit"></span></button>
          </a>
          <form action="{{ url_for('recipe.delete_recipe') }}" style="display: inline;" method="post">
            <button type="submit" name ="recipe_id" value="{{ recipe.id }}" class="btn btn-danger" style="padding: 5px; padding-bottom: 2px;"><span class="glyphicon glyphicon-trash"></span></button>
          </form>
          <h3 style="display: inline;"><b>{{ recipe.name }}</b></h3>
        </li>
        <ul>
          {% for step in recipe.steps %}
          <li><b>{{ step.num }}</b> - {{ step.description }}</li>
          {% endfor %}
          <ul>
            {% for ingredient in recipe.quantity %}
            <li>
              {{ ingredient.amount }} {{ ingredient.measurement_obj.name }} {{ ingredient.ingredient_obj.name }}
              <form action="{{ url_for('recipe.delete_ingredient') }}" method="post">
                <input type="hidden" name ="recipe_id" value="{{ recipe.id }}" />
              </form>
            </li>
            {% endfor %}
          </ul>
        </ul>
      {% endfor %}
    </table>
    <div class="col-md-1"></div>
  </div>
</div>
{% endblock %}